/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, Card, DatePicker, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import dayjs from 'dayjs'
import api from '../../api/axios'; import { API_ENDPOINTS } from '../../lib/constants'

const states:any={PENDING:['Chờ duyệt','orange'],APPROVED:['Đã duyệt - chờ giao','blue'],REJECTED:['Từ chối','red'],DELIVERED:['Đã giao - chờ nhận','cyan'],COMPLETED:['Hoàn tất','green']}
export default function TransfersPage(){
 const qc=useQueryClient(); const [open,setOpen]=useState(false); const [search,setSearch]=useState(''); const [form]=Form.useForm()
 const {data=[],isLoading}=useQuery({queryKey:['transfers',search],queryFn:()=>api.get(API_ENDPOINTS.TRANSFERS.BASE,{params:{search}}).then(r=>r.data.data)})
 const {data:equipment=[]}=useQuery({queryKey:['equipment-transfer'],queryFn:()=>api.get(API_ENDPOINTS.EQUIPMENT.BASE,{params:{per_page:500}}).then(r=>r.data.data)})
 const {data:orgs=[]}=useQuery({queryKey:['organizations-list'],queryFn:()=>api.get(API_ENDPOINTS.ORGANIZATIONS.BASE).then(r=>r.data.data)})
 const refresh=()=>{qc.invalidateQueries({queryKey:['transfers']});qc.invalidateQueries({queryKey:['equipment']})}
 const create=useMutation({mutationFn:(v:any)=>api.post(API_ENDPOINTS.TRANSFERS.BASE,{...v,requested_date:dayjs(v.requested_date).format('YYYY-MM-DD')}),onSuccess:r=>{message.success(r.data.message);setOpen(false);form.resetFields();refresh()},onError:(e:any)=>message.error(e.response?.data?.message)})
 const action=useMutation({mutationFn:({id,type,data}:{id:number,type:string,data?:any})=>api.post(`${API_ENDPOINTS.TRANSFERS.BASE}/${id}/${type}`,data),onSuccess:r=>{message.success(r.data.message);refresh()},onError:(e:any)=>message.error(e.response?.data?.message)})
 const reject=(id:number)=>Modal.confirm({title:'Từ chối điều chuyển',content:<Input.TextArea id="reject-note" placeholder="Vui lòng nhập lý do từ chối"/>,onOk:()=>{const notes=(document.getElementById('reject-note') as HTMLTextAreaElement)?.value;if(!notes){message.warning('Nhập lý do từ chối');return Promise.reject()} return action.mutateAsync({id,type:'reject',data:{notes}})}})
 const buttons=(r:any)=><Space wrap>{r.status==='PENDING'&&<><Button type="primary" onClick={()=>action.mutate({id:r.id,type:'approve'})}>Duyệt</Button><Button danger onClick={()=>reject(r.id)}>Từ chối</Button></>}{r.status==='APPROVED'&&<Button type="primary" onClick={()=>action.mutate({id:r.id,type:'handover'})}>Bên giao xác nhận</Button>}{r.status==='DELIVERED'&&<Button type="primary" onClick={()=>action.mutate({id:r.id,type:'complete'})}>Bên nhận hoàn tất</Button>}</Space>
 const cols:any[]=[{title:'Mã phiếu',dataIndex:'code'},{title:'Tài sản',render:(_:any,r:any)=><><b>{r.equipment?.name}</b><div className="text-xs">{r.equipment?.equipment_code}</div></>},{title:'Bộ phận giao',render:(_:any,r:any)=>r.from_organization?.name},{title:'Bộ phận nhận',render:(_:any,r:any)=>r.to_organization?.name},{title:'Lý do',dataIndex:'reason'},{title:'Trạng thái',render:(_:any,r:any)=><Tag color={(states[r.status]||[r.status,'default'])[1]}>{(states[r.status]||[r.status])[0]}</Tag>},{title:'Thao tác',render:(_:any,r:any)=>buttons(r)}]
 return <div className="space-y-5"><div className="flex justify-between"><div><h1 className="page-title">Luân chuyển tài sản</h1><p className="page-subtitle">Yêu cầu → phê duyệt → bàn giao → bên nhận xác nhận</p></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>{form.setFieldsValue({requested_date:dayjs()});setOpen(true)}}>Tạo yêu cầu</Button></div><Card><Input.Search placeholder="Vui lòng nhập mã phiếu hoặc tài sản" onSearch={setSearch}/><Table className="mt-4" rowKey="id" loading={isLoading} dataSource={data} columns={cols}/></Card>
 <Modal title="Tạo yêu cầu điều chuyển" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} confirmLoading={create.isPending}><Form form={form} layout="vertical" onFinish={v=>create.mutate(v)}><Form.Item name="equipment_id" label="Tài sản" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={equipment.map((e:any)=>({value:e.id,label:`${e.equipment_code} - ${e.name} (${e.organization?.name||'Chưa phân bổ'})`}))}/></Form.Item><Form.Item name="to_organization_id" label="Bộ phận nhận" rules={[{required:true}]}><Select options={orgs.map((o:any)=>({value:o.id,label:o.name}))}/></Form.Item><Form.Item name="requested_date" label="Ngày yêu cầu" rules={[{required:true}]}><DatePicker className="w-full"/></Form.Item><Form.Item name="reason" label="Lý do" rules={[{required:true}]}><Input.TextArea/></Form.Item><Form.Item name="notes" label="Ghi chú"><Input.TextArea/></Form.Item></Form></Modal></div>
}
